### PR TITLE
feat: least feature sync with Casbin.NET 2.x.

### PR DESCRIPTION
**Pull request by AsakusaRinne**
Currently, the efcore-adapter is corresponding to ```Casbin.NET 1.x```. In this PR, it's synchronized with ```Casbin.NET 2.x``` at the lowest limit.

### CODE REVIEW

**Comment by AsakusaRinne** [comment]
@sagilio Could you please help to see the build workflow? It seems ```Casbin 2.0.0``` could not be found. However, either in my local environment or the workflow in ```casbin-aspnetcore``` could succeed with the same package name.

**Comment by hsluoyz** [comment]
@AsakusaRinne isn't it already there? https://www.nuget.org/packages/Casbin.NET/2.0.0-preview.4

**Comment by sagilio** [comment]
> @sagilio Could you please help to see the build workflow? It seems `Casbin 2.0.0` could not be found. However, either in my local environment or the workflow in `casbin-aspnetcore` could succeed with the same package name.

This has been supported by https://github.com/casbin-net/efcore-adapter/pull/61, by it may lack some update policy API, you can continue to work based on this branch.

**Comment by AsakusaRinne** [comment]
> 

OK, I'll work on it. Thank you

**Comment by AsakusaRinne** [comment]
This is a duplicated PR, I'll close it.

**Comment by hsluoyz** [comment]
@AsakusaRinne dup with which PR?

**Comment by AsakusaRinne** [comment]
> @AsakusaRinne dup with which PR?

It's duplicated with #61 in preview branch. Since there may be some lack of features in #61, I'll continue to work on preview branch in the future.

**Pull request closed without merging**
