### PR TITLE
fix #20 rollback EfCore package version to 2.1.14

### LINKED ISSUE #20: Is it a proper choice if we remain a requirement of EF Core 2.x ?
I noticed that the nuget package forced requires EF Core >=3.1.3 from v1.2.0. 
image
I briefly checked the latest code and there's no conflict with EF Core 2.x.
As Casbin.NET package still support netstandard2.0(netcore 2.x),how about remain EF Core 2.x requirement until Casbin.NET package update? There is some [breaking changes in ef core 3.x](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes).some of old project is still based on netCore2.x LTS and ef core 2.x

### PR DESCRIPTION
**Pull request by arthuridea**
fix #20

### CODE REVIEW

**Comment by hsluoyz** [comment]
@arthuridea can we remove these two useless commits?

image

**Comment by Sagilio** [comment]
I think we can rollback to `2.1.14` because the `.net core 2.1` is LTS version.

**Comment by arthuridea** [comment]
> @arthuridea can we remove these two useless commits?
> 
> image

yes.

**Comment by hsluoyz** [comment]
Please rework these commits, finally we expect only one commit in this PR.

**Comment by arthuridea** [comment]
> I think we can rollback to `2.1.14` because of the `.net core 2.1` is the `LTS` version.

I think your advice is reasonable.I only followed the previous dependency version of EFCore but LTS version is more competiable.

**Comment by hsluoyz** [comment]
@Sagilio is it OK now?

**Comment by Sagilio** [comment]
> > I think we can rollback to `2.1.14` because of the `.net core 2.1` is the `LTS` version.
> 
> I think your advice is reasonable.I only followed the previous dependency version of EFCore but LTS version is more competiable.

Can you reset (--mixed) to 6c00c48 (Fix decide pull request condition error) commit and force push the last commit 74e5c53 (Change reference EF Core package version back to 2.1.14), thank you.

**Comment by hsluoyz** [comment]
@Sagilio that's OK. Maybe he doesn't know how to do it. We can squash it.

**Comment by arthuridea** [comment]
@hsluoyz @Sagilio  thanks.sorry for my fault. :(   I'll try to rebase squash my local commit history first next time.

**Pull request merged**
