### PR TITLE
Update Casbin.NET to 1.3.1 and add async unit tests

### PR DESCRIPTION
**Pull request by Sagilio**
If we use the `3.1.5` version of the `Microsoft.EntityFrameworkCore.Sqlite`, it will throw an error like this:
```ini
System.MissingMethodException : Method not found: 
'System.Threading.Tasks.Task`1<Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry`1<Int32>> 
Microsoft.EntityFrameworkCore.DbSet`1.AddAsync(Int32, System.Threading.CancellationToken)'
```
The EF Core main version should be same when we call async API, I think we need to consider how to handle the compatibility for `EF Core 2.x`.

### CODE REVIEW

**Comment by xcaptain** [comment]
I think you need to push Casbin.NET to support .net core 3 then we can use efcore 3 here.

**Comment by Sagilio** [comment]
@xcaptain  `Casbin.NET` is also a `netstandard2.0` project. When using async API It looks like we can not reference the 2.X version of  `Microsoft.EntityFrameworkCore` to keep the package can be used by both `EF Core 2.x` and `3.X`. We can add a 'netcoreapp2.1' target framework for 'EF Core 2.X'.
Do you have any idea about this? @arthuridea

**Comment by xcaptain** [comment]
https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes

图片

`AddAsync` has breaking change between efcore 2 and efcore 3, don't know how we can keep compatibility between the 2 version

**Comment by hsluoyz** [comment]
@huazhikui @xcaptain @nodece please review.

**Comment by arthuridea** [comment]
what will happen if someone create a project under target framework 3.x with ef core 2.x? Can we determine EfCore version in code then use sth. like preprocessor to choose the correct API version?

**Comment by xcaptain** [comment]
@arthuridea I think casbin's dbcontext has nothing to do with the application's dbcontext. I found I have a lot of efcore version installed.
图片

If the app and library use different efcore, they will coexist rather than choose the closest version.

**Comment by Sagilio** [comment]
@xcaptain @arthuridea  I think we can try to provide a new package for legacy LTS targets, like `Casbin.NET.Adapter.EFCore21` and all target packages reference the package `Casbin.NET.Adapter.EFCore.Core`. The `Casbin.NET.Adapter.EFCore` package will always reference the latest release.

**Comment by xcaptain** [comment]
@Sagilio I agree with you, maintaining 2 versions is ok, I think there 2 ways to do this

1. use git branch and cherry pick to maintain 2 versions
2. create another folder to hold the efcore 2.x code

I prefer using branch, because very soon people will give up .net core 2 so we don't have too much code needs to port from master to v2 branch

**Comment by arthuridea** [comment]
@Sagilio I agree.It seems that we can't satisfy both  EfCore versions.Leaving a legacy version of nuget package for is considerable。I think we need to make an effort to name it clearly without confusing to each other

**Comment by arthuridea** [comment]
@xcaptain Is there a way that we can use sth. like DefineConstants in project file to solve this issue without creating lots of branches? unfortunately I know little about this

**Pull request merged**
