### PR TITLE
add generic support

### PR DESCRIPTION
**Pull request by arthuridea**

### CODE REVIEW

**Comment by xcaptain** [comment]
So this pull request is to support non-int primary key id for `casbin_rule` table? This field is not required for other adapter implementations like gorm, xorm, but EFcore requires every table has a primary key, so it was added here.

Are you using a Uuid id or other string type id? this pull request looks good to me, but would be good to have more discusses.

**Comment by arthuridea** [comment]
> So this pull request is to support non-int primary key id for `casbin_rule` table? This field is not required for other adapter implementations like gorm, xorm, but EFcore requires every table has a primary key, so it was added here.
> 
> Are you using a Uuid id or other string type id? this pull request looks good to me, but would be good to have more discusses.

yes.I use an auto generated Guid string as primary key with custom EntityTypeConfiguration in my project. It works well for me.

**Comment by hsluoyz** [comment]
@huazhikui

**Comment by xcaptain** [comment]
Hello, this change has been published at https://www.nuget.org/packages/Casbin.NET.Adapter.EFCore/1.1.0 @arthuridea Can you verify it?

@hsluoyz @huazhikui the CI auto deploy function works well, set a new version in the csproj file and then create a tag on github will trigger travis to deploy to nuget

**Pull request merged**
