### PR TITLE
fix: Upgrade to net6 and 7

### PR DESCRIPTION
**Pull request by sociometry**
Fixes: #59 (and also upgrade to net7)

### CODE REVIEW

**Review by sagilio — APPROVED** [review]

**Comment by sagilio** [comment]
@sociometry Please fix the ci failed:
image

**Comment by hsluoyz** [comment]
@sagilio do we need to upgrade to 7? Does it impact the compatibility?

**Comment by sagilio** [comment]
> @sagilio do we need to upgrade to 7? Does it impact the compatibiNolity?

No, no impact on anything, different targets are built separately.

**Comment by hsluoyz** [comment]
@sagilio @sociometry why the semantic-release is not triggered?

**Comment by kalkin** [comment]
Thank you very much.

**Pull request merged**
