### PR TITLE
First commit

### PR DESCRIPTION
**Pull request by AaqibAhamed**
Coding standard and best practices has been checked

### CODE REVIEW

**Comment by xcaptain** [comment]
Just formated some code?

**Comment by AaqibAhamed** [comment]
yes.I have just formatted some code.I'm a GSoC student.I'm just initiated code base understanding and setting up the working environment .

**Comment by xcaptain** [comment]
Merged, thanks!

**Comment by xcaptain** [comment]
@AaqibAhamed Since the dotnet core 3.1 has released for a long time, do you have interest to upgrade the dependencies of this project to latest?

**Comment by xcaptain** [comment]
https://github.com/casbin-net/EFCore-Adapter/issues/12

**Comment by AaqibAhamed** [comment]
Yeah sure.I'll do it

**Comment by AaqibAhamed** [comment]
This issue has been solved.I have send a Pull request,check it and merged with origin/master.

**Comment by AaqibAhamed** [comment]
> Thanks for the help, look at this issue pls. 😄
> 
> #12
The issue #12 has been solved.I have send a Pull request,check it and merged with origin/master.

**Pull request merged**
